version: '3.8'

services:
  datastream-viewer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://root:7Apf5U8xLNLExWcS@mongodev.int.qubeyond.com:27017/QuDataStream?readPreference=primaryPreferred&replicaSet=rs0&authSource=admin}
      - DB_NAME=${DB_NAME:-QuDataStream}
      - COLLECTION_NAME=${COLLECTION_NAME:-ReceivedEvents}
      - AUTH_USER=${AUTH_USER:-dspublisher}
      - AUTH_PASS=${AUTH_PASS:-D4taStr3am!}
    restart: unless-stopped
